controller:
  cascade_controllers:
  - name: "joint1"
    inner:
      Kp: 260.4594
      Ki: 1953.4457
      Kd: 0.0
    outer:
      Kp: 5.0
      Ki: 0.0
      Kd: 0.0
  - name: "joint2"
    inner:
      Kp: 21.3716
      Ki: 160.2867
      Kd: 0.0
    outer:
      Kp: 5.0
      Ki: 0.0
      Kd: 0.0


model_parameters:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0


